<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSznajvb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSznajvb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSznajvb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSznajvb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSznajvb\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Sznajvb',
    'container.build_id' => 'b646ee0e',
    'container.build_time' => 1522095662,
));
