<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLkvik5l\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLkvik5l/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLkvik5l.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLkvik5l\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLkvik5l\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Lkvik5l',
    'container.build_id' => '4a6fea33',
    'container.build_time' => 1522414222,
));
