<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUw0b3bw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUw0b3bw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUw0b3bw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUw0b3bw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUw0b3bw\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Uw0b3bw',
    'container.build_id' => 'f954b7fe',
    'container.build_time' => 1522915351,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUw0b3bw');
