<?php

namespace AppBundle\Repository;

/**
 * PoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoisRepository extends \Doctrine\ORM\EntityRepository
{
}
